### ISSUE TITLE
JetBrains Rider support

### ISSUE THREAD

**Issue by IncPlusPlus** [xBlackCat/ice-framework-idea-plugin#1]
Hi there. Does this plugin support Rider? It seems to crash on startup. I can provide some logs if you like. I can reliably reproduce the crash. I'm on Rider 2019.3 and the latest version of your plugin.

**Comment by xBlackCat** [comment]
Please, attach the logs to the issue.

**Comment by xBlackCat** [comment]
Unfortunately, Rider has completely different plugin structure in compare to IntelliJ Idea. I'm sorry but currently it is not possible to build the plugin with Rider support
