### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by jianrongfeng** [xBlackCat/ice-framework-idea-plugin#3]
The configuration ICE home in IDEA is ok, but how to execute slicetojava in this plugin?

**Comment by xBlackCat** [comment]
In Idea UI add facet "ZeroC" to your module in Project Structure View. In the facet configuration you can choose target language translator and target directory.
Files are generated on build project command or you can force generate files by selecting Ice file and choose 'Recompile <file>' option from context menu.

**Comment by jianrongfeng** [comment]
Thanks for your reply. I have done the first step,  I tried "build project" without effort and the "Recompile" option was disabled.
Screenshot is below:
![微信截图_20200812112940](https://user-images.githubusercontent.com/11880963/89973300-97e62600-dc92-11ea-94e2-10b28d68ce34.png)
![微信截图_20200812113133](https://user-images.githubusercontent.com/11880963/89973317-a16f8e00-dc92-11ea-9e41-11b43922c72f.png)

**Comment by xBlackCat** [comment]
Put the Test.ice file into sources folder: into your src/main/java or better create a new one like (src/main/ice and mark it as "sources" in project structure).
![image](https://user-images.githubusercontent.com/1286054/89979663-f9010000-dc78-11ea-83f9-a81444f48048.png)

**Comment by jianrongfeng** [comment]
Yes i do that, but nothing is generated.

**Comment by xBlackCat** [comment]
Could you please attach your project to the issue to check configuration?

**Comment by jianrongfeng** [comment]
Sorry, I don't understand it, are you mean "Modules" configuration?

**Comment by xBlackCat** [comment]
zip your Ice-demo folder content and attach to the issue. I could  check project configuration and tell you what is missing in configuration

**Comment by jianrongfeng** [comment]
Thanks very much, You are so kind !
[code.zip](https://github.com/xBlackCat/ice-framework-idea-plugin/files/5066659/code.zip)

**Comment by xBlackCat** [comment]
For the first, *.ice files must be located in **'Sources'** folder (not 'Resources')

I'm recommending to create a separate sources folder for *.ice files.

I've created a new folder /src/main/ice in your project and marked it as 'Sources'. Put to the folder your Test.ice file and invoke 'Recompile file' command: slice translator was started.

![image](https://user-images.githubusercontent.com/1286054/90102090-8eb79080-dd48-11ea-9c42-aab6366cc5c0.png)

Ensure your settings is correct for Ice translator location:
![image](https://user-images.githubusercontent.com/1286054/90102183-bd356b80-dd48-11ea-8027-2951ce726a72.png)

And Facet configuration in the module:
![image](https://user-images.githubusercontent.com/1286054/90102242-d5a58600-dd48-11ea-917d-c53f015fd324.png)

**Comment by jianrongfeng** [comment]
Great! 
I have generated successfully!
Thank you for your help.
